### ISSUE TITLE
Making forecasts beyond the length of the training time series

### ISSUE THREAD

**Issue by emilyblack** [brightlego/general_tamsat_alert#8]
the code will not create forecasts beyond the end of the training time series. 

For example, if I have a dataset that finishes on 1/5/2024, and try to make a forecast starting on 1/5/2023 for a poi of 1/10/2023 - 1/12/2023, it works fine
![image](https://github.com/brightlego/general_tamsat_alert/assets/32983722/dd4df28a-8a55-4eb5-8691-07740d6b8a09)

However, if I try to make a forecast, starting on 1/5/2024 for a poi of 1/10/2024 - 1/12/2024, it produces erroneous results: 
![image](https://github.com/brightlego/general_tamsat_alert/assets/32983722/148f73fb-2b44-4b39-bc71-2a3eb864d0a9)

As a workaround, the training time series can be padded with dummy data but this is obviously clunky. Any help would be appreciated.

**Comment by brightlego** [comment]
I have updated the code to allow for extrapolation of the poi to beyond the extent of the data. Install version 1.2.2 of the module for these changes to take effect. Additionally, further issues should be raised on the [https://github.com/TAMSAT/general_tamsat_alert](url) fork
